wolfizen_net/apps/main/urls.py
import os

from django.conf import settings
from django.templatetags.static import static
from django.urls import path, re_path

from wolfizen_net.apps.main.views import *


app_name = "main"
urlpatterns = [
    path(
        "",
        RootPageView.as_view(),
        name="root",
    ),
    re_path(
        r"^infinite/(?P<depth>\d+)$",
        InfiniteLinksView.as_view(),
        name="infinite-links",
    ),
    re_path(
        r"^pet-registration/(?P<pet_id>\w+)$",
        PetRegistrationView.as_view(),
        name="pet-registration",
    ),
    path(
        "rainbow",
        RainbowTextView.as_view(),
        name="rainbow-text"
    ),
    # Asset aliases
    path(
        "resume.pdf",
        RedirectViewKeepMethod.as_view(
            url=static("main/Resumé.pdf"),
            permanent=False),
        name="resume",
    ),
    path(
        "refsheet",
        RedirectViewKeepMethod.as_view(
            url=static("main/2022-02-12_Holt-Odium_Refsheet_Standard_5400.png"),
            permanent=False),
        name="resume",
    ),
    path(
        "refsheet-nsfw",
        RedirectViewKeepMethod.as_view(
            url=static("main/2022-02-12_Holt-Odium_Refsheet_Extended_5400.png"),
            permanent=False),
        name="resume",
    ),
    # External redirects
    path(
        "ddnswolf",
        RedirectViewKeepMethod.as_view(
            url="https://github.com/Wolfizen/DDNSWolf",
            permanent=False),
        name="ddnswolf",
    ),
]

wolfizen_net/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path("", include('wolfizen_net.apps.main.urls')),
]

# Serve media files in debug mode, just like static files.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wolfizen_net/models.py
from django.db import models


class ShowVote(models.Model):
    show = models.ForeignKey('wolfizen_net.Show', on_delete=models.CASCADE, related_name='votes')
    source_ip = models.GenericIPAddressField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} -> {} @ {}".format(self.source_ip, self.show.name, self.created_at)


class Show(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} @ {}".format(self.name, self.created_at)

wolfizen_net/forms.py
from django.forms import ModelForm, Form
from django.forms.models import ModelChoiceField

from wolfizen_net.models import Show


class CreateShowForm(ModelForm):
    class Meta:
        model = Show
        fields = ['name']


class VoteForm(Form):
    show = ModelChoiceField(queryset=Show.objects.all())

wolfizen_net/apps/main/views.py
from ipaddress import IPv6Address, IPv4Address
from typing import Any

from django.http import FileResponse, Http404
from django.http.response import HttpResponseRedirectBase, HttpResponseGone
from django.views.generic import TemplateView
from django.views.generic.base import View, RedirectView

from wolfizen_net.apps.main import util
from wolfizen_net.apps.main.util import CachedViewMixin


class RootPageView(CachedViewMixin, TemplateView):
    template_name = "main/root.html"

    def get_context_data(self, **kwargs):
        context = super(RootPageView, self).get_context_data(**kwargs)
        client_addr = util.get_client_address(self.request)
        context['request_is_ipv6'] = isinstance(client_addr, IPv6Address)
        context['request_is_ipv4'] = isinstance(client_addr, IPv4Address)
        return context


class InfiniteLinksView(CachedViewMixin, TemplateView):
    template_name = "main/infinite.html"

    def get_context_data(self, **kwargs):
        context = super(InfiniteLinksView, self).get_context_data(**kwargs)
        current_depth = int(context['depth'])
        context['depth'] = current_depth
        context['next_depth'] = current_depth + 1
        context['prev_depth'] = current_depth - 1
        return context


class PetRegistrationView(CachedViewMixin, TemplateView):
    template_name = "main/pet-registration.html"

    pets: dict[str, dict[str, Any]] = {
        "tala": {
            "name": "Tala Luna",
            "species": "Canis lupus",
            "variant": "Northwestern wolf",
            "variant_meta_name": "Subspecies",
            "fur_color": "Gray",
            "eye_color": "Amber",
            "weight": "40 kg",
            "photo_path": "main/2020-03-14_Elkir_spirit_of_the_forest_icon_1914.png",
            "accent_color": "#5fb0ff",
        },
        "quill": {
            "name": "Quill Luna",
            "species": "Canis familiaris",
            "variant": "Border Collie",
            "variant_meta_name": "Breed",
            "fur_color": "Black & white",
            "eye_color": "Blue",
            "weight": "17 kg",
            "photo_path": "main/2021-08-19_Holt-Odium_Quill_Refsheet_BG_feral_icon_666.png",
            "accent_color": "#4f367e",
        },
    }

    def get_context_data(self, **kwargs):
        context = super(PetRegistrationView, self).get_context_data(**kwargs)

        pet_id = context.get("pet_id", "")
        if pet_id in self.pets:
            context.update(self.pets[pet_id])

        return context


class RainbowTextView(CachedViewMixin, TemplateView):
    template_name = "main/rainbow.html"


class FileView(CachedViewMixin, View):
    """
    This custom view will serve any specified file.

    as_view() accepts two arguments:
        file_path: The path to the file. Recommended: `os.path.join(TEMPLATE_DIR, ...)`
        content_type: The MIME-type of the file.
    """

    file_path = None
    content_type = None

    def get(self, request, *args, **kwargs):
        try:
            return FileResponse(
                open(self.file_path, 'rb'),
                content_type=self.content_type)
        except FileNotFoundError:
            raise Http404()


class RedirectViewKeepMethod(RedirectView):

    def get(self, request, *args, **kwargs):
        url = self.get_redirect_url(*args, **kwargs)
        if url:
            if self.permanent:
                return HttpResponsePermanentRedirectKeepMethod(url)
            else:
                return HttpResponseRedirectKeepMethod(url)
        else:
            return HttpResponseGone()

    def dispatch(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class HttpResponseRedirectKeepMethod(HttpResponseRedirectBase):
    status_code = 307


class HttpResponsePermanentRedirectKeepMethod(HttpResponseRedirectBase):
    status_code = 308

wolfizen_net/views.py
from django.db.models import Count, F, Subquery, Sum, Case, When
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import TemplateView, CreateView
from django.views.generic.list import ListView

from wolfizen_net.forms import CreateShowForm, VoteForm
from wolfizen_net.models import Show, ShowVote


class RootPageView(TemplateView):
    template_name = "wolfizen_net/root.html"


class InfiniteRecursionView(TemplateView):
    template_name = "wolfizen_net/infinite.html"

    def get_context_data(self, **kwargs):
        context = super(InfiniteRecursionView, self).get_context_data(**kwargs)
        context['depth'] = int(context['depth'])
        context['next_depth'] = context['depth'] + 1
        context['prev_depth'] = context['depth'] - 1
        return context


class RainbowTextView(TemplateView):
    template_name = "wolfizen_net/rainbow.html"


class ShowListView(ListView):
    template_name = "wolfizen_net/rsfa_voting.html"
    model = Show

    def get_context_data(self, **kwargs):
        context = super(ShowListView, self).get_context_data(**kwargs)
        source_ip = get_client_ip(self.request)
        for show in context['object_list']:
            show.has_voted = ShowVote.objects.filter(show_id=show.id, source_ip=source_ip).exists()
        return context


class CreateShowView(CreateView):
    template_name = "wolfizen_net/create_show.html"
    form_class = CreateShowForm
    success_url = reverse_lazy('rsfa-voting')

    def form_valid(self, form):
        # Duplicate code from super, to add code between save() and returning response
        self.object = form.save()
        ShowVote.objects.create(show=self.object, source_ip=get_client_ip(self.request))
        return HttpResponseRedirect(self.get_success_url())


class VoteView(View):
    success_url = reverse_lazy('rsfa-voting')

    def post(self, request):
        source_ip = get_client_ip(self.request)
        print("Received vote from IP: {}".format(source_ip))
        form = VoteForm(request.POST)
        if form.is_valid():
            show = form.cleaned_data['show']
            if not ShowVote.objects.filter(show_id=show.id, source_ip=source_ip).exists():
                ShowVote.objects.create(source_ip=source_ip, show=show)
            else:
                print("Tried to vote for same show: {}".format(source_ip))
        else:
            # TODO
            print("Invalid form: {}".format(form.errors))
        return redirect(reverse('rsfa-voting'))


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        return request.META.get('HTTP_X_REAL_IP')
    else:
        return request.META.get('REMOTE_ADDR')

wolfizen_net/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="data:,">
    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

wolfizen_net/templates/main/infinite.html
{% extends 'main/base.html' %}

{% block extra_head %}
    <title>∞ | wolfizen.net</title>
    {% if depth == 0 %}
    <meta name="robots" content="index, nofollow">
    {% else %}
    <meta name="robots" content="noindex, nofollow">
    {% endif %}
{% endblock extra_head %}

{% block content %}
    <h1>You are on level {{ depth }}</h1>
    <p>
        {% if prev_depth >= 0 %}
        <a href="{% url 'main:infinite-links' depth=prev_depth %}">Up a level</a>
        |
        {% endif %}
        <a href="{% url 'main:infinite-links' depth=next_depth %}">Down a level</a>
    </p>
    <hr/>
    <p>
        <a href="{% url 'main:root' %}">Home</a>
    </p>
{% endblock content %}

wolfizen_net/templates/main/pet-registration.html
{% extends 'main/base.html' %}

{% load static %}

{% block extra_head %}
    <title>Pet Registration | wolfizen.net</title>
    <meta name="robots" content="noindex, follow">
    <style>
        body {
            background-color: black;
            color: white;
            font-family: sans;
        }

        a {
            color: gray;
        }

        .identification {
            display: inline-flex;
            flex-direction: column;
            margin: 1rem;
            overflow: hidden;
            border-radius: 0.7rem;
            background-color: #333333;
        }

        .identification header {
            display: inline-flex;
            justify-content: space-between;
            background-color: {{ accent_color }};
            font-size: 18px;
        }

        .identification header > * {
            margin: 1rem;
            font-size: 1em;
        }

        .identification header svg {
            height: 1em;
            fill: currentColor;
        }

        .identification section {
            display: inline-flex;
            align-items: flex-start;
        }

        .identification section img.identification-photo {
            height: 6rem;
            margin: 1rem;
            border-radius: 0.2rem;
            border-color: white;
            border-style: solid;
            border-width: 1px;
        }

        .identification section table {
            margin: 1rem;
            margin-left: 0;
            background-color: #444444;
            border-radius: 0.2rem;
            border-spacing: 0.3rem;
        }

        .identification section table td:nth-child(1) {
            text-align: right;
            font-size: 0.8em;
        }
    </style>
{% endblock extra_head %}

{% block content %}
    <figure class="identification">
        <header>
            <h1>Pet Identification Card</h1>
            <svg viewBox="0 0 400 400">
                <use href="{% static 'main/animal-track.svg' %}#group0" />
            </svg>
        </header>
        <section>
            <img
                class="identification-photo"
                title="Identification photo"
                alt="identification photo"
                src="{% static photo_path %}"
            />
            <table>
                <tr>
                    <td>Name</td>
                    <td><strong>{{ name }}</strong></td>
                </tr>
                <tr>
                    <td>Species</td>
                    <td><i>{{ species }}</i></td>
                </tr>
                <tr>
                    <td>{{ variant_meta_name }}</td>
                    <td>{{ variant }}</td>
                </tr>
                <tr>
                    <td>Fur color</td>
                    <td>{{ fur_color }}</td>
                </tr>
                <tr>
                    <td>Eye color</td>
                    <td>{{ eye_color }}</td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td>{{ weight }}</td>
                </tr>
            </table>
        </section>
    </figure>

    <div>
        Some icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a>
        from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
    </div>
{% endblock content %}

wolfizen_net/templates/main/petregistration.html
{% extends 'main/base.html' %}

{% load static %}

{% block extra_head %}
    <title>Pet Registration | wolfizen.net</title>
    <meta name="robots" content="noindex, follow">
    <style>
        body {
            background-color: black;
            color: white;
            font-family: sans;
        }

        a {
            color: gray;
        }

        .identification {
            display: inline-flex;
            flex-direction: column;
            margin: 1rem;
            overflow: hidden;
            border-radius: 0.7rem;
            background-color: #333333;
        }

        .identification header {
            display: inline-flex;
            justify-content: space-between;
            background-color: {{ accent_color }};
            font-size: 18px;
        }

        .identification header > * {
            margin: 1rem;
            font-size: 1em;
        }

        .identification header svg {
            height: 1em;
            fill: currentColor;
        }

        .identification section {
            display: inline-flex;
            align-items: flex-start;
        }

        .identification section img.identification-photo {
            height: 6rem;
            margin: 1rem;
            border-radius: 0.2rem;
            border-color: white;
            border-style: solid;
            border-width: 1px;
        }

        .identification section table {
            margin: 1rem;
            margin-left: 0;
            background-color: #444444;
            border-radius: 0.2rem;
            border-spacing: 0.3rem;
        }

        .identification section table td:nth-child(1) {
            text-align: right;
            font-size: 0.8em;
        }
    </style>
{% endblock extra_head %}

{% block content %}
    <figure class="identification">
        <header>
            <h1>Pet Identification Card</h1>
            <svg viewBox="0 0 400 400">
                <use href="{% static 'main/animal-track.svg' %}#group0" />
            </svg>
        </header>
        <section>
            <img
                class="identification-photo"
                title="Identification photo"
                alt="identification photo"
                src="{% static photo_path %}"
            />
            <table>
                <tr>
                    <td>Name</td>
                    <td><strong>{{ name }}</strong></td>
                </tr>
                <tr>
                    <td>Species</td>
                    <td><i>{{ species }}</i></td>
                </tr>
                <tr>
                    <td>{{ variant_meta_name }}</td>
                    <td>{{ variant }}</td>
                </tr>
                <tr>
                    <td>Fur color</td>
                    <td>{{ fur_color }}</td>
                </tr>
                <tr>
                    <td>Eye color</td>
                    <td>{{ eye_color }}</td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td>{{ weight }}</td>
                </tr>
            </table>
        </section>
    </figure>

    <div>
        Some icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a>
        from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
    </div>
{% endblock content %}

wolfizen_net/templates/main/rainbow.html
{% extends 'main/base.html' %}

{% block extra_head %}
    <title>Rainbow Text | wolfizen.net</title>
    <style>
        body, html {
            height: 99%; /** Fix scrollbar appearing on 100% */
        }
        #groovy {
            display: block;
            width: 100%;
            height: 100%;
            margin: auto;
            text-align: center;

            border: none;
            background: none;
            font-size: 18pt;
        }
    </style>
    <script type="text/javascript">
        var colorTime = 0,
            waveTheta = 0,
            maxCount = 100,
            colorIncrement = -12,
            waveIncrement = 0.1,
            xPos = [ -2, -1, 0, 1, 2 ],
            yPos = [ -2, -1, 0, 1, 2 ],
            props = {};

        var getTextShadow = function( x, y, hue ) {
          return ', ' + x + 'px ' + y + 'px hsl(' + hue + ', 100%, 50%)';
        };

        var animate = function() {
          var shadows = '0 0 transparent',
              hue0 = colorTime % 360,
              i, j, x, y,
              iLen = xPos.length,
              jLen = yPos.length;

          // outline
          for ( i = 0; i < iLen; i++ ) {
            x = xPos[i];
            for ( j = 0; j < jLen; j++ ) {
              y = yPos[j];
              shadows += getTextShadow( x, y, hue0 );
            }
          }

          // renders rainbow river
          for ( i = 1; i < maxCount; i++ ) {
            var normI = i / maxCount,
                hue = ( normI * 360 * 2 + colorTime ) % 360;
            x = ~~( ( Math.sin( normI * Math.PI * 2 + waveTheta ) - Math.sin( waveTheta ) )  * 50 );
            y = i * 3;
            shadows += getTextShadow( x, y, hue );
          }

          props.groovy.style.textShadow = shadows;
          colorTime += colorIncrement;
          waveTheta += waveIncrement;
          setTimeout( animate, 30 );
        };

        var init = function() {

          props.groovy = document.getElementById('groovy');

          setTimeout( animate, 1 );

        };

        window.addEventListener( 'DOMContentLoaded', init, false);
    </script>
{% endblock extra_head %}

{% block content %}
    <textarea id="groovy">Edit me!</textarea>
{% endblock content %}

wolfizen_net/templates/main/root.html
{% extends 'main/base.html' %}

{% load static %}

{% block extra_head %}
    <title>wolfizen.net</title>
    <style>
        /* Font */
        {% include 'main/overpass-mono.css' %}
        body {
            text-align: center;
            font-family: 'Overpass Mono', monospace;
        }

        img {
            max-width: 100%; /* Responsive images, size down on mobile devices */
            color: red; /* Style the alt-text (if it does not load properly) */
        }

        /* Center tables */
        table {
            margin-left: auto;
            margin-right: auto;
            /*border: 0;*/
        }

        /* Center-aligned text appearance within the links table */
        #links-table td:nth-child(1) {text-align: right;}
        #links-table td:nth-child(3) {text-align: left;}

        /* Animated background */
        /* https://codepen.io/P1N2O/pen/pyBNzX */
        html {
            min-height: 100%;
        }
        body {
            color: #fff;
            background: linear-gradient(45deg, #73e9e0, #922fc4);
            background-size: 400% 400%;
            background-repeat: no-repeat;
            -webkit-animation: animated-bg 15s ease infinite;
            -moz-animation: animated-bg 15s ease infinite;
            animation: animated-bg 15s ease infinite;
        }
        @-webkit-keyframes animated-bg {
            0% {background-position: 0% 50%}
            50% {background-position: 100% 50%}
            100% {background-position: 0% 50%}
        }
        @-moz-keyframes animated-bg {
            0% {background-position: 0% 50%}
            50% {background-position: 100% 50%}
            100% {background-position: 0% 50%}
        }
        @keyframes animated-bg {
            0% {background-position: 0% 50%}
            50% {background-position: 100% 50%}
            100% {background-position: 0% 50%}
        }
    </style>
{% endblock extra_head %}

{% block content %}
    <figure>
        <img src="{% static 'main/2018-06-15_sleepygills_sassy_icon_512_transparent.png' %}" alt="wolfizen profile icon" />
        <figcaption>Image credit: <a href="https://furaffinity.net/user/sleepygills">sleepygills</a></figcaption>
    </figure>
    <h1>wolfizen.net</h1>
    <p>
        I'm Winona. You may also know me as Wolfizen. This is my website!<br/>
        I have links here to many of my profiles on other places online, and projects I have made.
    </p>
    <table id="links-table">
        <tr>
            <td>Github</td>
            <td>:</td>
            <td><a href="https://github.com/Wolfizen">Wolfizen</a></td>
        </tr>
        <tr>
            <td>Telegram</td>
            <td>:</td>
            <td><a href="https://telegram.me/Wolfizen">@Wolfizen</a></td>
        </tr>
        <tr>
            <td>SoundCloud</td>
            <td>:</td>
            <td><a href="https://soundcloud.com/wolfizen">Wolfizen</a></td>
        </tr>
    </table>
    <h2>Projects</h2>
    <p>
        <a href="https://projectret.ro">Project: Retro</a>
        <a href="{% url 'main:ddnswolf' %}">DDNSWolf</a>
    </p>
    <h2>Friends</h2>
    <p>
        <a href="https://anchovie.art/">Anchovie</a>
        <a href="https://hecate.space/">Hecate</a>
        <a href="https://deers.io/">West</a>
    </p>
    <h2>Silly Things</h2>
    <p>
        <a href="{% url 'main:infinite-links' depth=0 %}">Infinite links</a>
        <a href="{% url 'main:rainbow-text' %}">Rainbow text</a>
    </p>
    <footer>
        <a href='http://ipv6-test.com'>
            {% if request_is_ipv6 %}
                <img src="{% static 'main/ipv6-test-v6-white.png' %}" alt="IP test badge showing a test result of v6" title="You connected to this site via IPv6"/>
            {% elif request_is_ipv4 %}
                <img src="{% static 'main/ipv6-test-v4-white.png' %}" alt="IP test badge showing a test result of v4" title="You connected to this site via IPv4"/>
            {% else %}
                <span style="color: red">IP version test failure :(</span>
            {% endif %}
        </a>
    </footer>
{% endblock content %}